[package]
name = "marketplace"
version = "1.0.0"
authors = []

[addresses]
marketplace_addr = "_"
nft_addr = "_"

[dev-addresses]
marketplace_addr = "0x8f54"
nft_addr = "0x8ac0"

[dependencies]
AptosFramework = {git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects"}

 